name: "GitHub Classroom Pytest Grader"
author: "Alexander Richards"
description: "A Pytest grader without fixing the Python environment."
inputs:
  timeout:
    description: "Duration (in minutes) before the test is terminated. Defaults to 10 minutes with a maximum limit of 60 minutes."
    default: "10"
    required: true
  max-score:
    description: "The maximum amount of points a student can receive for this test."
    required: false
  setup-command:
    description: "Command to execute prior to the test, typically for environment setup or dependency installation."
    required: false
outputs:
  result:
    description: "Runner output"
runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: python -m pip install ${{github.action_path}}
    - name: Run Autograder
      shell: bash
      run: |
        python ${{github.action_path}}/run.py
        ls -l my_report.json
        {
          echo "result<<EOF"
          cat my_report.json
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        #echo "result=`cat my_report.json`" >> $GITHUB_OUTPUT
        # echo "result=$result" >> $GITHUB_OUTPUT
